[package]
name = "junta-service"
version = "0.1.0"
authors = ["Rasmus Kildevaeld <rasmuskildevaeld@gmail.com>"]
edition = "2018"

[dependencies]
future-ext = { git = "https://github.com/kildevaeld/future-ext" }
futures = "^0.1"


[dev-dependencies]
void = "^1.0"
tokio = "^0.1"